a = 1
b = [a, 2]
c = {a: b[0]}
d = (a, b, c)
e = {a}
f = (a & 2 * 3) - 33 / 2
g = b + [1]
h = ~a
i = a if a else h
k = b[1:2]
l = [(x, x * 2) for x in b]
m = {x : y for x in b for y in e}
n, o, p = 1, "st", True
nn = n
oo = o
pp = p


# a := int
# b := List[int]
# c := Dict[int, int]
# d := Tuple[int, List[int], Dict[int, int]]
# e := Set[int]
# f := float
# g := List[int]
# h := int
# i := int
# k := List[int]
# l := List[Tuple[int, int]]
# m := Dict[int, int]
# n := int
# o := str
# p := bool
