a = 1 + 2 / 3
b = -a
c = [1.2, 2.0, b]
d = [[1.1, 2.5], c]
e = {(i, i * 2) for j in d for i in j}
f = 2 & 3
g = d[f]
h = (g, 2.0, a)
i, j, (k, (l, m)) = {1: 2.0}, True, ((1, 2), (f, e))
n = a if True else "string"
o = (1 is 2)
condition = True
q = [3] if condition else ["st"]
r = [2.0] and [1, 2]
s = q + r
t = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
u = 2
v = 8
w = t[u:v:u]
x = w[u]

# a := float
# b := float
# c := List[float]
# d := List[List[float]]
# e := Set[Tuple[float, float]]
# f := int
# g := List[float]
# h := Tuple[List[float], float, float]
# i := Dict[int, float]
# j := bool
# k := Tuple[int, int]
# l := int
# m := Set[Tuple[float, float]]
# n := object
# o := bool
# t := List[int]
# u := int
# v := int
# w := List[int]
# x := int
